name: CI/CD Deploy Angular Docker

on:  
  push: 
    branches: [ "master" ]
    
jobs:     
  ci_cd_deploy_angular:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“ Show initial files
        run: ls -la

      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v2

      - name: ğŸ“ Show files after checkout
        run: ls -la

      - name: âš™ï¸ Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: ğŸ“¦ Install dependencies 
        run: npm ci

      - name: ğŸ› ï¸ Build Angular app
        run: npm run build --prod

      - name: ğŸ“ List Angular build output
        run: ls -la dist/api-apuestas  # AsegÃºrate de que esta ruta sea correcta

      - name: ğŸ³ Build Docker image with NGINX
        run: docker build -t ${{ secrets.DOCKER_USER }}/api-apuestas-angular:${{ github.sha }} .

      - name: ğŸ§± List Docker images
        run: docker images

      - name: ğŸ” Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸš€ Push Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/api-apuestas-angular:${{ github.sha }}
